### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Wertzui123** [AndreasHGK/MultiPort#2] opened 2019-05-14 19:37 UTC
I can't join to my server with another port than the default...

**Comment by andreashgk** [comment] 2019-05-14 19:38
Is the port forwarded?
Does your host allow you to use this port?

**Comment by Wertzui123** [comment] 2019-05-14 19:38
I don't know. I use minehub.de

**Comment by andreashgk** [comment] 2019-05-14 19:39
Yes, they probably only allow you to use 1 port. Ask them to open a second one for you. Duplicate of #1

**Closed as completed by andreashgk** 2019-05-14 19:39 UTC

**Comment by Wertzui123** [comment] 2019-05-14 19:43
Okey, sorry
